// swift-tools-version: 6.3

import PackageDescription

// MPVBUILD_BINARY_TARGETS_BEGIN — Generated by Build/mpvbuild; selection: remote
private let binaryTargets: [Target] = [
    .binaryTarget(name: "Libmpv-GPL", url: "https://github.com/LePips/MPVUI/releases/download/0.3.0/Libmpv.xcframework.zip", checksum: "6f0d7feed77fc2cf2917d21604bff478faf1dd91a7fb86071b1d53a43785c3b1"),
]
// MPVBUILD_BINARY_TARGETS_END

let package = Package(
    name: "MPVUI",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
    ],
    products: [
        .library(
            name: "MPVUI",
            targets: ["MPVUI"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-docc-plugin", from: "1.1.0"),
    ],
    targets: [
        .target(
            name: "MPVUI",
            dependencies: [
                "Libmpv-GPL",
                .target(name: "_MPVUIPictureInPicture", condition: .when(platforms: [.macOS])),
            ],
            path: "Sources",
            exclude: ["Player/PictureInPicture/_MPVUIPictureInPicture"],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AVKit"),
                .linkedFramework("CoreImage"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreText"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("Foundation"),
                .linkedFramework("IOSurface"),
                .linkedFramework("Metal"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("Security"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("AppKit", .when(platforms: [.macOS])),
                .linkedFramework("OpenGL", .when(platforms: [.macOS])),
                .linkedFramework("IOKit", .when(platforms: [.macOS])),
                .linkedFramework("UIKit", .when(platforms: [.iOS, .tvOS, .visionOS])),
                .linkedLibrary("bz2"),
                .linkedLibrary("iconv"),
                .linkedLibrary("expat"),
                .linkedLibrary("resolv"),
                .linkedLibrary("xml2"),
                .linkedLibrary("z"),
                .linkedLibrary("c++"),
            ]
        ),
        .target(
            name: "_MPVUIPictureInPicture",
            path: "Sources/Player/PictureInPicture/_MPVUIPictureInPicture",
            publicHeadersPath: "include",
            linkerSettings: [.linkedFramework("AppKit", .when(platforms: [.macOS]))]
        ),
        .testTarget(
            name: "MPVUITests",
            dependencies: [
                "MPVUI",
                "Libmpv-GPL",
            ],
            path: "Tests",
            plugins: [.plugin(name: "GenerateTestMedia")]
        ),
        .plugin(name: "GenerateTestMedia", capability: .buildTool()),
    ] + binaryTargets,
    swiftLanguageModes: [.v6]
)
