// swift-tools-version: 6.3

import PackageDescription

// MPVBUILD_BINARY_TARGETS_BEGIN — Generated by Build/mpvbuild; selection: remote
private let binaryTargets: [Target] = [
    .binaryTarget(name: "Libmpv-GPL", url: "https://github.com/LePips/MPVUI/releases/download/0.1.1/Libmpv.xcframework.zip", checksum: "2cac3b64db0e2c88ba38f444389d1496387637424370c487d8b2a45618649289"),
]
// MPVBUILD_BINARY_TARGETS_END

let package = Package(
    name: "MPVUI",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
    ],
    products: [
        .library(
            name: "MPVUI",
            targets: ["MPVUI"]
        ),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "MPVUI",
            dependencies: [
                "Libmpv-GPL",
            ],
            path: "Sources",
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreText"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("Foundation"),
                .linkedFramework("IOSurface"),
                .linkedFramework("Metal"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("Security"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("AppKit", .when(platforms: [.macOS])),
                .linkedFramework("OpenGL", .when(platforms: [.macOS])),
                .linkedFramework("IOKit", .when(platforms: [.macOS])),
                .linkedFramework("UIKit", .when(platforms: [.iOS, .tvOS, .visionOS])),
                .linkedLibrary("bz2"),
                .linkedLibrary("iconv"),
                .linkedLibrary("expat"),
                .linkedLibrary("resolv"),
                .linkedLibrary("xml2"),
                .linkedLibrary("z"),
                .linkedLibrary("c++"),
            ]
        ),
        .testTarget(
            name: "MPVUITests",
            dependencies: [
                "MPVUI",
                "Libmpv-GPL",
            ],
            path: "Tests",
            resources: [.copy("Resources/Media")]
        ),
    ] + binaryTargets,
    swiftLanguageModes: [.v6]
)
