// swift-tools-version: 6.3

import PackageDescription

// MPVBUILD_BINARY_TARGETS_BEGIN — Generated by Build/mpvbuild; selection: local
private let binaryTargets: [Target] = [
    .binaryTarget(
        name: "Libmpv-GPL",
        path: ".build/mpvbuild-local/selections/fed901e5db2692794042a52db6f17bffad8cdbb9aa85c716a34f97cc6a686c12/Libmpv-GPL.xcframework"
    ),
]
// MPVBUILD_BINARY_TARGETS_END

let package = Package(
    name: "MPVUI",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
    ],
    products: [
        .library(
            name: "MPVUI",
            targets: ["MPVUI"]
        ),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "MPVUI",
            dependencies: [
                "Libmpv-GPL",
                .target(name: "_MPVUIPictureInPicture", condition: .when(platforms: [.macOS])),
            ],
            path: "Sources",
            exclude: ["Player/PictureInPicture/_MPVUIPictureInPicture"],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AVKit"),
                .linkedFramework("CoreImage"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreText"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("Foundation"),
                .linkedFramework("IOSurface"),
                .linkedFramework("Metal"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("Security"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("AppKit", .when(platforms: [.macOS])),
                .linkedFramework("OpenGL", .when(platforms: [.macOS])),
                .linkedFramework("IOKit", .when(platforms: [.macOS])),
                .linkedFramework("UIKit", .when(platforms: [.iOS, .tvOS, .visionOS])),
                .linkedLibrary("bz2"),
                .linkedLibrary("iconv"),
                .linkedLibrary("expat"),
                .linkedLibrary("resolv"),
                .linkedLibrary("xml2"),
                .linkedLibrary("z"),
                .linkedLibrary("c++"),
            ]
        ),
        .target(
            name: "_MPVUIPictureInPicture",
            path: "Sources/Player/PictureInPicture/_MPVUIPictureInPicture",
            publicHeadersPath: "include",
            linkerSettings: [.linkedFramework("AppKit", .when(platforms: [.macOS]))]
        ),
        .target(
            name: "MPVUITestResources",
            path: "Example/MPVUIExample/Shared/Resources",
            resources: [.copy("Media"), .copy("Fixtures.lock.json")]
        ),
        .testTarget(
            name: "MPVUITests",
            dependencies: [
                "MPVUI",
                "Libmpv-GPL",
                "MPVUITestResources",
            ],
            path: "Tests",
            resources: [.copy("Resources/Media"), .copy("Resources/Fixtures.lock.json")]
        ),
    ] + binaryTargets,
    swiftLanguageModes: [.v6]
)
